FROM node:alpine

# Add a work directory
WORKDIR /usr/src/app

# COPY package*.json ./
COPY package*.json ./

# Cache and Install dependencies
RUN npm cache clean --force && npm cache verify
RUN rm -rf node_modules && rm -rf package-lock.json

WORKDIR /usr/src/app
RUN npm install

# Copy app files
COPY ./ ./

# Expose port
EXPOSE 4000

# Start the app
# RUN npm run dev

CMD ["npm", "start"]