version: '3.9'

services:
  mongodb:
    build:
      context: mongodb
      dockerfile: Dockerfile
    image: mern_mongodb:1.0
    container_name: mern_mongodb
    volumes:
      - .\mongodb\data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mern_stack
    ports:
      - "27017:27017"
    restart: always

  nodejs:
    depends_on:
      - mongodb
    build:
      context: backend
      dockerfile: Dockerfile.prod
    image: mern_nodejs:1.0
    container_name: mern_nodejs
    volumes:
      - /usr/app/node_modules
      - .\backend:/usr/app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SALT=${SALT}
      - BACKEND_PORT=${BACKEND_PORT}
      - CONNECTION_STRING=${CONNECTION_STRING}
    ports:
      - "5500:5500"
    networks:
      - mern_stack
    restart: always
  react:
    depends_on:
      - mongodb
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    image: mern_react:1.0
    container_name: mern_react
    volumes:
      - /usr/app/node_modules
      - .\frontend:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
    ports:
      - "8081:80"
    networks:
      - mern_stack
    restart: always

networks:
  mern_stack:
    name: mern_stack
    driver: bridge
