# เอา image ที่มี node ลงไว้แล้วมา
# FROM node:14 as base

# # สร้าง folder /app ใน image ขึ้นมารอ
# # RUN mkdir -p /app

# # เปลี่ยน (หรือ set) working dir ใน image เป็น /app
# WORKDIR /home/node/app

# # ก๊อบป
# COPY package*.json ./

# #
# RUN npm install

# COPY . .

# # FROM base as production

# # ENV NODE_PATH=./build

# # RUN npm run build

# # Build
# RUN npm run build

# # สั่ง node /app/server.j
# CMD ["node", "/app/index.js"]

# # เปิดพอร์ท 3000
# EXPOSE 8000


FROM node:lts-alpine

WORKDIR /usr/src/app

# COPY package*.json ./
COPY package*.json ./

# RUN npm cache clean --force
# RUN npm cache verify
# RUN rm -rf node_modules && rm -rf package-lock.json && npm i
# RUN npm update
RUN npm cache clean --force && npm cache verify
RUN rm -rf node_modules && rm -rf package-lock.json

WORKDIR /usr/src/app
RUN npm install
# RUN apk add –no-cache make gcc g++ python && npm install && npm rebuild bcrypt –build-from-source && apk del make gcc g++ python

# If you are building your code for production
# RUN npm ci --only=production

# copy codebase to docker codebase
COPY . .

EXPOSE 8000

RUN npm run build

CMD [ "node", "dist/index.js" ]

